# Generated by Django 5.2.10 on 2026-02-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slogan', models.CharField(default='감이 아니라 근거로 실험하세요.', max_length=200)),
                ('run_budget', models.PositiveSmallIntegerField(default=8)),
                ('response_name', models.CharField(default='수율(Yield, %)', max_length=50)),
                ('goal', models.CharField(default='maximize', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_no', models.PositiveSmallIntegerField()),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
                ('x4', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='doe.project')),
            ],
            options={
                'ordering': ['run_no'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='doe.project')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='doe.designrun')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveSmallIntegerField()),
                ('name_kr', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='doe.project')),
            ],
            options={
                'ordering': ['idx'],
                'constraints': [models.UniqueConstraint(fields=('project', 'idx'), name='uq_factor_project_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='designrun',
            constraint=models.UniqueConstraint(fields=('project', 'run_no'), name='up_run_project_runno'),
        ),
    ]
