# Generated by Django 5.2.14 on 2026-05-10 07:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_order', models.PositiveSmallIntegerField()),
                ('levels', models.JSONField()),
                ('values', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_runs', to='doe.project')),
            ],
            options={
                'ordering': ['run_order'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.DecimalField(decimal_places=4, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='doe.designrun')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('name_kr', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='doe.project')),
            ],
            options={
                'ordering': ['idx'],
                'constraints': [models.UniqueConstraint(fields=('project', 'idx'), name='unique_factor_idx_per_project')],
            },
        ),
        migrations.AddConstraint(
            model_name='designrun',
            constraint=models.UniqueConstraint(fields=('project', 'run_order'), name='unique_run_order_per_project'),
        ),
    ]
