# Generated by Django 5.2.14 on 2026-07-25 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doe', '0008_resulthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('landing_path', models.CharField(blank=True, max_length=500)),
                ('referrer_url', models.URLField(blank=True, max_length=1000)),
                ('referrer_source', models.CharField(blank=True, db_index=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=160)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doe_visitor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('home_viewed', 'Home viewed'), ('wizard_started', 'Wizard started'), ('design_generated', 'Design generated'), ('results_saved', 'Results saved'), ('report_viewed', 'Report viewed')], db_index=True, max_length=40)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='doe.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doe_analytics_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='doe.visitorsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='doe_analyti_event_n_0937f5_idx'), models.Index(fields=['session', 'created_at'], name='doe_analyti_session_b8d767_idx')],
            },
        ),
    ]
