# Generated by Django 5.2.14 on 2026-08-01 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doe', '0009_visitorsession_analyticsevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('inquiry', '사용 방법 문의'), ('bug', '오류 신고'), ('improvement', '개선 제안')], max_length=20)),
                ('message', models.TextField(max_length=4000)),
                ('page', models.CharField(blank=True, max_length=80)),
                ('step', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('new', '새 문의'), ('in_progress', '확인 중'), ('resolved', '처리 완료')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='doe.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doe_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
