# Generated by Django 5.2.14 on 2026-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doe', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='attachment_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
